In [1]:
#Practice read CSV

In [2]:
import pandas as pd
csv_movies = pd.read_csv (r"C:\Users\SHWETA\Downloads\imdb-top-1000 (1).csv")

In [3]:
csv_movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [4]:
csv_movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [5]:
#dataframe---rows and colunm
csv_movies.shape

(1000, 10)

In [6]:
csv_movies.columns

Index(['Series_Title', 'Released_Year', 'Runtime', 'Genre', 'IMDB_Rating',
       'Director', 'Star1', 'No_of_Votes', 'Gross', 'Metascore'],
      dtype='str')

In [7]:
csv_movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   str
 1   Released_Year  1000 non-null   str
 2   Runtime        1000 non-null   int64
 3   Genre          1000 non-null   str
 4   IMDB_Rating    1000 non-null   float64
 5   Director       1000 non-null   str
 6   Star1          1000 non-null   str
 7   No_of_Votes    1000 non-null   int64
 8   Gross          1000 non-null   float64
 9   Metascore      843 non-null    float64
dtypes: float64(3), int64(2), str(5)
memory usage: 78.3 KB

In [8]:
csv_movies.dtypes

Series_Title         str
Released_Year        str
Runtime            int64
Genre                str
IMDB_Rating      float64
Director             str
Star1                str
No_of_Votes        int64
Gross            float64
Metascore        float64
dtype: object

In [9]:
#colunms select
csv_movies["Series_Title"]

0      The Shawshank Redemption
1                 The Godfather
2               The Dark Knight
3        The Godfather: Part II
4                  12 Angry Men
                 ...
995      Breakfast at Tiffany's
996                       Giant
997       From Here to Eternity
998                    Lifeboat
999                The 39 Steps
Name: Series_Title, Length: 1000, dtype: str

In [10]:
csv_movies[["Series_Title","IMDB_Rating"]]

                 Series_Title  IMDB_Rating
0    The Shawshank Redemption          9.3
1               The Godfather          9.2
2             The Dark Knight          9.0
3      The Godfather: Part II          9.0
4                12 Angry Men          9.0
..                        ...          ...
995    Breakfast at Tiffany's          7.6
996                     Giant          7.6
997     From Here to Eternity          7.6
998                  Lifeboat          7.6
999              The 39 Steps          7.6

[1000 rows x 2 columns]

In [11]:
#movie title directors rating votes
csv_movies[["Series_Title","Director","IMDB_Rating","No_of_Votes"]]

                 Series_Title              Director  IMDB_Rating  No_of_Votes
0    The Shawshank Redemption        Frank Darabont          9.3      2343110
1               The Godfather  Francis Ford Coppola          9.2      1620367
2             The Dark Knight     Christopher Nolan          9.0      2303232
3      The Godfather: Part II  Francis Ford Coppola          9.0      1129952
4                12 Angry Men          Sidney Lumet          9.0       689845
..                        ...                   ...          ...          ...
995    Breakfast at Tiffany's         Blake Edwards          7.6       166544
996                     Giant        George Stevens          7.6        34075
997     From Here to Eternity        Fred Zinnemann          7.6        43374
998                  Lifeboat      Alfred Hitchcock          7.6        26471
999              The 39 Steps      Alfred Hitchcock          7.6        51853

[1000 rows x 4 columns]

In [12]:
#filtering
#imdb rating 8.5 se greating movies show karo
csv_movies[csv_movies["IMDB_Rating"]>8.5]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
6,Pulp Fiction,1994,154,Crime,8.9,Quentin Tarantino,John Travolta,1826188,107928762.0,94.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
8,Inception,2010,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0
9,Fight Club,1999,139,Drama,8.8,David Fincher,Brad Pitt,1854740,37030102.0,66.0
10,The Lord of the Rings: The Fellowship of the Ring,2001,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0
11,Forrest Gump,1994,142,Drama,8.8,Robert Zemeckis,Tom Hanks,1809221,330252182.0,82.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
14,The Matrix,1999,136,Action,8.7,Lana Wachowski,Lilly Wachowski,1676426,171479930.0,73.0
15,Goodfellas,1990,146,Biography,8.7,Martin Scorsese,Robert De Niro,1020727,46836394.0,90.0
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
17,One Flew Over the Cuckoo's Nest,1975,133,Drama,8.7,Milos Forman,Jack Nicholson,918088,112000000.0,83.0
18,Hamilton,2020,160,Biography,8.6,Thomas Kail,Lin-Manuel Miranda,55291,440984783.0,90.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
20,Soorarai Pottru,2020,153,Drama,8.6,Sudha Kongara,Suriya,54995,556832648.0,NaN
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
22,Cidade de Deus,2002,130,Crime,8.6,Fernando Meirelles,Kátia Lund,699256,7563397.0,79.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
24,Saving Private Ryan,1998,169,Drama,8.6,Steven Spielberg,Tom Hanks,1235804,216540909.0,91.0
25,The Green Mile,1999,189,Crime,8.6,Frank Darabont,Tom Hanks,1147794,136801374.0,61.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
28,The Silence of the Lambs,1991,118,Crime,8.6,Jonathan Demme,Jodie Foster,1270197,130742922.0,85.0
29,Star Wars,1977,121,Action,8.6,George Lucas,Mark Hamill,1231473,322740140.0,90.0
30,Seppuku,1962,133,Action,8.6,Masaki Kobayashi,Tatsuya Nakadai,42004,373978394.0,85.0
31,Shichinin no samurai,1954,207,Action,8.6,Akira Kurosawa,Toshirô Mifune,315744,269061.0,98.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0

In [31]:
csv_movies["Released_Year"] = pd.to_numeric(csv_movies["Released_Year"], errors ='coerce')

In [32]:
csv_movies[csv_movies["Released_Year"]>2000]

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
5,The Lord of the Rings: The Return of the King,2003.0,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
8,Inception,2010.0,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0
10,The Lord of the Rings: The Fellowship of the Ring,2001.0,178,Action,8.8,Peter Jackson,Elijah Wood,1661481,315544750.0,92.0
13,The Lord of the Rings: The Two Towers,2002.0,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
...,...,...,...,...,...,...,...,...,...,...
947,Harry Potter and the Sorcerer's Stone,2001.0,152,Adventure,7.6,Chris Columbus,Daniel Radcliffe,658185,317575550.0,64.0
948,The Others,2001.0,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
949,Blow,2001.0,124,Biography,7.6,Ted Demme,Johnny Depp,240714,52990775.0,52.0
950,Enemy at the Gates,2001.0,131,Drama,7.6,Jean-Jacques Annaud,Jude Law,243729,51401758.0,53.0
951,Minority Report,2002.0,145,Action,7.6,Steven Spielberg,Tom Cruise,508417,132072926.0,80.0